# -*- coding: utf-8 -*-
"""similar_Word.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IaU487DxTSbLZUqHv4rw6HTDYlDXexgb
"""

from sklearn.metrics.pairwise import cosine_similarity
from gensim.models import Word2Vec # Import Word2Vec for text_to_vector

# Example sentences and query
sentences = [
    "The car is fast and sleek.",
    "I love driving my sports car.",
    "The dog is loyal and friendly.",
    "My cat is very playful."
]
query = "fast car"

# Function to convert text to vector using Word2Vec
def text_to_vector(text):
    """Converts a string of text into a numerical vector using Word2Vec.

    Args:
        text: The input text string.

    Returns:
        A numerical vector representing the text.
    """
    words = text.lower().split()
    vectors = [model.wv[word] for word in words if word in model.wv] # Get vectors for words in vocabulary
    if vectors:
        return sum(vectors) / len(vectors)  # Average the word vectors
    else:
        return [0] * model.vector_size  # Return a zero vector if no words are found

# Compute embeddings for sentences and query
sentence_vectors = [text_to_vector(sentence) for sentence in sentences]
query_vector = text_to_vector(query)

# Find the most similar sentence
similarities = cosine_similarity([query_vector], sentence_vectors)
most_similar_idx = similarities.argmax()
print("Query:", query)
print("Most similar sentence:", sentences[most_similar_idx])